version: '3.9'

services:
  firewall:
    build: ./NGFW_Docker/.
    restart: always
    ports:
      - 9999:9999
    volumes:
      - userdata:/var/log/apache2/
      - ./html:/var/www/html
      - ./script/:/root/script/
      - ./NGFW-with-VPN-Filteration/:/root

volumes:
  userdata:

      