version: '3.9'

services:
  firewall:
    build: ./NGFW_Docker/.
    restart: always
    ports:
      - 9999:9999
    volumes:
      - userdata:/var/log/apache2/
      - ./NGFW_Docker/html:/var/www/html
      - ./NGFW_Docker/script/:/root/script/
      - ./NGFW_Docker/NGFW-code/:/root/

volumes:
  userdata:

      